### ISSUE TITLE
Missing icons in configs

### ISSUE THREAD

**Issue by skrekkugle** [ImRayy/dotfiles#1]
The configs seem to be missing the icons

**Comment by ImRayy** [comment]
> The configs seem to be missing the icons

Icons are part of  [Nerd Fonts](https://www.nerdfonts.com/). To access these icons, it's essential to install any Nerd Font. The fonts I use are listed in README file.

**Comment by skrekkugle** [comment]
Thanks!

**Comment by ImRayy** [comment]
> Thanks!

Welcome:)
